namespace Storyboarding.Tools

module Resources =
    let square_black = "effects/128square.png"
    let square_white = "effects/128square_white.png"
    let fog = "effects/fog.png"
    let glow_ray = "effects/glow_ray.png"
    let glow_ray_rotated = "effects/glow_ray_rotated.png"
    let ineffective_light = "effects/light.png"
    let light = "effects/light2.png"
    let light_dot = "effects/light_dot.png"
    let light_squashed = "effects/light_squashed.png"
    let light_thin = "effects/light_thin.png"
    let ping = "effects/ping.png"
    let ping_thin = "effects/ping_thin.png"
    let grad_ray = "effects/grad_ray.png"
    let rain_drop_w = "effects/droplet_ring_w.png"
    let rain_drop_b = "effects/droplet_ring_b.png"
    let rain_droplet = "effects/droplet.png"
    let water_normal = "effects/water_b_2.png"
    let spark_droplet = "effects/spark_droplet.png"
    let spark_line = "effects/spark_line.png"
    let triangle_white = "effects/triangle128.png"
    let circle_dotted = "effects/circle_dotted.png"
    let black_circle = "effects/black_circle.png"
    let gradient = "effects/grad.png"
    let vignette = "effects/vignette_black.png"
    let screen_overlay = "effects/screen_overlay_2.png"
    let rib = "effects/rib.png"
    let star = "effects/star.png"
    let dot = "effects/dot.png"

    let e_bubble i = $"effects/bubbles/bubble_{i}.png"

    let fhd = ImageFilters.resizeToFHD
    let qhd = ImageFilters.resizeTo 2560 1440

    let bg_lights = fhd "bg/aa-lights.jpg"
    let bg_twins_upper = fhd "bg/LeKWYk_upper.jpg"
    let bg_twins_lower = fhd "bg/LeKWYk_lower.jpg"
    let bg_twins_lower_masked = fhd "bg/LeKWYk_lower_rain_mask.png"
    let bg_twins = fhd "bg/LeKWYk.jpg"
    let bg_burning_heart = fhd "bg/burning_heart.jpg"
    let bg_burning_heart_raw = fhd "bg/q9WmNL.png"
    let bg_grayish_sky = fhd"bg/5Xzmxw_cut.jpg"
    let bg_warrior_on_a_log = fhd"bg/1N6mmX.jpg"
    let bg_burning_city = fhd "bg/1476171916-1.jpg"
    let bg_desert_sunset = fhd "bg/OmONLv.jpg"
    let bg_mountains_sunset = fhd "bg/GXkwJB.jpg"
    let bg_campfire = fhd "bg/L4R68K.jpg"
    let bg_sidetracked_day = fhd "bg/n0mwQo.jpg"
    let bg_snow_mountain = qhd "bg/snow_mountain.jpg"
    let bg_sunmoonstars = fhd "bg/sunmoonstars.jpg"
    let bg_isolation = qhd "bg/5ZqBg.jpg"
    let bg_leaves = qhd "bg/leaves.jpg"
    let bg_fern = fhd "bg/fern.jpg"

    let bg_hidamari_1 = "bg/hidamari/1.jpg"
    let bg_hidamari_2 = "bg/hidamari/2.jpg"
    let bg_hidamari_3 = "bg/hidamari/3.jpg"
    let bg_hidamari_4 = "bg/hidamari/4.jpg"

    let font_finger_paint = "font/FingerPaint-Regular.ttf"
    let font_monomach = "font/Monomakh-Regular.ttf"
    let font_monosans = "font/MonaSans-Light.ttf"
    let font_text_me_one = "font/TextMeOne-Regular.ttf"
    let font_notosans_jp = "font/NotoSansJP-Regular.ttf"
    let font_notoserif_jp = "font/NotoSerifJP-Light.ttf"
    let font_quicksand = "font/Quicksand-Light.ttf"
    let font_quicksand_bold = "font/Quicksand-SemiBold.ttf"
    let font_jetbrains_mono = "font/JetBrainsMono-Light.ttf"
    let font_smooch_sans = "font/SmoochSans-Light.ttf"
    let font_quartez = "font/QuartezRegular.otf"
    let font_forum = "font/Forum-Regular.ttf"

    let gp_simple_circle = "gameplay/simple_circle.png"
    let gp_simple_approach_circle = "gameplay/approach_circle.png"
    let gp_filled_circle = "gameplay/filled_circle.png"
    let gp_dot32 = "gameplay/dot32.png"
    let gp_square32 = "gameplay/square32.png"

    let shape_triangle = "effects/shapes/shape_triangle.png"
    let shape_cross = "effects/shapes/shape_cross.png"
    let shape_lines = "effects/shapes/shape_lines.png"
    let shape_cube = "effects/shapes/shape_cube.png"
    let shape_circle_chevron = "effects/shapes/shape_circle_chevron.png"
    let shape_square = "effects/shapes/shape_square.png"
    let shape_line = "effects/shapes/shape_line.png"
    let golden_spiral = "effects/shapes/golden_spiral.png"

    let ui_progressbar_long_out = "effects/ui/progressbar_long_outer.png"
    let ui_progressbar_out = "effects/ui/progressbar_outer.png"

    let continuum_code = "effects/code/continuum.png"