namespace Storyboarding.Tools

module Resources =
    let resourcesFolder = @"C:\Users\arthur\Documents\Storyboarding\Storyboarding\Resources\"
    let scriptPath = @"C:\Users\arthur\Documents\Storyboarding\Storyboarding\Scripts"
    let savePathPrefix = @"C:\Users\arthur\Documents\Storyboarding\Storyboarding\Resources\font"
    let fontsFolder = @"C:\Users\arthur\Documents\Storyboarding\Storyboarding\Fonts"

    let square_black = "effects/128square.png"
    let square_white = "effects/128square_white.png"
    let fog = "effects/fog.png"
    let glow_ray = "effects/glow_ray.png"
    let light = "effects/light.png"
    let light_dot = "effects/light_dot.png"
    let ping = "effects/ping.png"
    let grad_ray = "effects/grad_ray.png"
    let rain_drop_w = "effects/droplet_ring_w.png"
    let rain_drop_b = "effects/droplet_ring_b.png"
    let rain_droplet = "effects/droplet.png"
    let water_normal = "effects/water_b_2.png"
    let spark_droplet = "effects/spark_droplet.png"
    let spark_line = "effects/spark_line.png"
    let triangle_white = "effects/triangle128.png"

    let bg_lights = "bg/aa-lights.jpg"
    let bg_twins_upper = "bg/LeKWYk_upper.jpg"
    let bg_twins_lower = "bg/LeKWYk_lower.jpg"
    let bg_twins_lower_masked = "bg/LeKWYk_lower_rain_mask.png"
    let bg_twins = "bg/LeKWYk.jpg"
    let bg_burning_heart = "bg/burning_heart.jpg"
    let bg_burning_heart_raw = "bg/q9WmNL.png"
    let bg_grayish_sky = "bg/5Xzmxw_cut.jpg"
    let bg_warrior_on_a_log = "bg/1N6mmX.jpg"
    let bg_burning_city = "bg/aonybJ.jpg"

    let font_finger_paint = "font/FingerPaint-Regular.ttf"
    let font_monomach = "font/Monomakh-Regular.ttf"
    let font_monosans = "font/MonaSans-Light.ttf"
    let font_text_me_one = "font/TextMeOne-Regular.ttf"

    let gp_simple_circle = "gameplay/simple_circle.png"
    let gp_simple_approach_circle = "gameplay/approach_circle.png"
    let gp_filled_circle = "gameplay/filled_circle.png"
    let gp_dot32 = "gameplay/dot32.png"
    let gp_square32 = "gameplay/square32.png"
